import os
import cv2
import numpy as np
from typing import List, Tuple, Optional, Dict
from tqdm import tqdm

from .mask_utils import (
    MaskCleaner,
    clean_binary_mask,
    clean_instance_mask,
    batch_clean_masks
)


class MaskPostProcessor:
    """
    Mask post-processor for automatically cleaning mask folders generated by Gaussian rendering.
    """
    
    def __init__(self, GS_dir: str, records_name: str):
        """
        Initialize post-processor.
        
        Args:
            GS_dir: Gaussian rendering output directory
            records_name: Records name
        """
        self.GS_records_dir = os.path.join(GS_dir, records_name)
    
    def clean_mask_folder(
        self,
        record_name: str,
        cam_name: str,
        rgb_folder_name: str,
        target_colors: List[Tuple[int, int, int]],
        method: str = 'nearest',
        output_suffix: str = '_clean',
        **kwargs
    ):
        """
        Clean single mask folder.
        
        Args:
            record_name: Record name
            cam_name: Camera name, e.g., 'cam_0'
            rgb_folder_name: RGB folder name, e.g., 'rgb_mask_object'
            target_colors: List of target colors in BGR format (0-255)
            method: Cleaning method
                - 'binary': Binary classification cleaning (recommended for single object mask)
                - 'instance': Instance segmentation cleaning (recommended for multi-object mask)
                - 'nearest': Nearest color mapping (general purpose)
                - 'cluster': K-means clustering (accurate but slow)
            output_suffix: Output folder suffix
                - '_clean': rgb_mask_object → rgb_mask_object_clean
                - '': In-place replacement (overwrite original files)
            **kwargs: Additional parameters
                - min_object_size: Minimum object size (pixels)
                - kernel_size: Morphological kernel size
                - tolerance: Color tolerance
        
        Example:
            # Clean binary mask
            processor.clean_mask_folder(
                'record_0', 'cam_0', 'rgb_mask_object',
                target_colors=[(0, 0, 0), (255, 255, 255)],  # Black and white
                method='binary'
            )
            
            # Clean instance segmentation mask
            processor.clean_mask_folder(
                'record_0', 'cam_0', 'rgb_mask_instance',
                target_colors=[(0, 0, 0), (0, 0, 255), (0, 255, 0), (255, 0, 0)],  # Black, red, green, blue
                method='instance'
            )
        """
        # Input and output folders
        input_folder = os.path.join(
            self.GS_records_dir, record_name, cam_name, rgb_folder_name
        )
        
        if output_suffix:
            output_folder_name = rgb_folder_name + output_suffix
        else:
            output_folder_name = rgb_folder_name
        
        output_folder = os.path.join(
            self.GS_records_dir, record_name, cam_name, output_folder_name
        )
        
        if not os.path.exists(input_folder):
            print(f"[Warning] Input folder not found: {input_folder}")
            return
        
        # Batch clean
        batch_clean_masks(
            input_folder, output_folder,
            target_colors, method,
            file_pattern='*.png',
            **kwargs
        )
        
        print(f"✅ Mask cleaned: {output_folder_name}")
    
    def clean_all_masks_in_record(
        self,
        record_name: str,
        mask_configs: List[Dict],
        cameras: Optional[List[str]] = None
    ):
        """
        Clean all masks in a record.
        
        Args:
            record_name: Record name
            mask_configs: List of mask configurations, each containing:
                {
                    'rgb_folder': 'rgb_mask_object',
                    'target_colors': [(0, 0, 0), (255, 255, 255)],
                    'method': 'binary',
                    'output_suffix': '_clean'
                }
            cameras: List of cameras, None means all cameras
        
        Example:
            processor.clean_all_masks_in_record(
                'record_0',
                mask_configs=[
                    {
                        'rgb_folder': 'rgb_mask_object',
                        'target_colors': [(0, 0, 0), (255, 255, 255)],
                        'method': 'binary'
                    },
                    {
                        'rgb_folder': 'rgb_mask_instance',
                        'target_colors': [(0, 0, 0), (0, 0, 255), (0, 255, 0)],
                        'method': 'instance'
                    }
                ],
                cameras=['cam_0', 'cam_1']
            )
        """
        # Get camera list
        if cameras is None:
            record_dir = os.path.join(self.GS_records_dir, record_name)
            cameras = [d for d in os.listdir(record_dir) if d.startswith('cam_')]
        
        for cam_name in cameras:
            print(f"\n[Info] Processing camera: {cam_name}")
            
            for config in mask_configs:
                rgb_folder = config['rgb_folder']
                target_colors = config['target_colors']
                method = config.get('method', 'nearest')
                output_suffix = config.get('output_suffix', '_clean')
                
                # Extract additional parameters
                extra_params = {
                    k: v for k, v in config.items()
                    if k not in ['rgb_folder', 'target_colors', 'method', 'output_suffix']
                }
                
                self.clean_mask_folder(
                    record_name, cam_name, rgb_folder,
                    target_colors, method, output_suffix,
                    **extra_params
                )
    
    def clean_all_records(
        self,
        mask_configs: List[Dict],
        cameras: Optional[List[str]] = None,
        record_indices: Optional[List[int]] = None
    ):
        """
        Clean masks in all records.
        
        Args:
            mask_configs: List of mask configurations
            cameras: List of cameras
            record_indices: List of record indices, None means all
        """
        # Get all records
        all_records = sorted([
            d for d in os.listdir(self.GS_records_dir)
            if d.startswith('record_')
        ])
        
        # Filter records to process
        if record_indices is not None:
            records_to_process = [all_records[i] for i in record_indices]
        else:
            records_to_process = all_records
        
        print(f"[Info] Starting batch cleaning, {len(records_to_process)} records")
        
        for record_name in tqdm(records_to_process, desc="Processing records", unit="record"):
            self.clean_all_masks_in_record(record_name, mask_configs, cameras)
        
        print("\n✅ Mask cleaning for all records complete")


if __name__ == "__main__":
    """Usage example"""
    
    # Example 1: Clean single mask folder
    processor = MaskPostProcessor(
        GS_dir="/home/student/new_data/GS_Data",
        records_name="records_1024_test"
    )
    
    processor.clean_mask_folder(
        record_name='record_0',
        cam_name='cam_0',
        rgb_folder_name='rgb_mask_object',
        target_colors=[(0, 0, 0), (255, 255, 255)],  # Black and white
        method='binary',
        min_object_size=100,
        kernel_size=5
    )
    
    # Example 2: Batch clean multiple masks
    mask_configs = [
        {
            'rgb_folder': 'rgb_mask_object',
            'target_colors': [(0, 0, 0), (255, 255, 255)],
            'method': 'binary',
            'min_object_size': 100,
            'kernel_size': 5
        },
        {
            'rgb_folder': 'rgb_mask_instance',
            'target_colors': [(0, 0, 0), (0, 0, 255), (0, 255, 0), (255, 0, 0)],
            'method': 'instance',
            'min_object_size': 50,
            'kernel_size': 3
        }
    ]
    
    processor.clean_all_masks_in_record(
        'record_0',
        mask_configs,
        cameras=['cam_0', 'cam_1']
    )
    
    print("\n✅ Test complete")
